### ISSUE TITLE
Editor crashing while loading

### ISSUE THREAD

**Issue by CycleCycIe** [InclementDab/DayZ-Editor#106]
The dayz editor says "no world map found for Deerisle" and crashes. If i load the deerisle mod it hangs on the splash screen while loading. I have re installed dayz and unsubed all mods, re subed to editor and dependencies. Still gives same result. I have tried rolling back graphics driver several versions, no effect. Dayz runs fine. Steam cloud save is turned off.
Any help would be great, its an amazing bit of kit when its working. 

![image](https://user-images.githubusercontent.com/111229632/184535904-ac563bda-ba68-45df-9d5b-ab4f3f9ad190.png)

**Comment by InclementDab** [comment]
This isnt a bug, you a mission in your parameters tab. remove and relaunch
