### ISSUE TITLE
Editor doesn't launch

### ISSUE THREAD

**Issue by Pipstapee** [InclementDab/DayZ-Editor#116]
As the title states, the editor doesn't launch. It didn't do it before the update, how can I restore the previous version?
The status bar goes about half way and then freezes, has a 0xC0000005 Status access violation, ay ideas?
Nothing has changed apart from the editor did an update, I had previously updated to 1.21 as I host my own dedicated server so I keep it updated.

**Comment by Pipstapee** [comment]
No one having the same issue or at least can offer any recommendation on a solution?

**Comment by InclementDab** [comment]
Thats because you arent supposed to run it on a server. It automatically shuts your server off if its running since it has unintended consequences
