### ISSUE TITLE
Object properties won’t bind

### ISSUE THREAD

**Issue by BBTDB** [InclementDab/DayZ-Editor#117]
I know this was an issue in the past, but it’s happening again. Even with all settings default, when a properties window is open and the settings are changed, the object doesn’t move to reflect the changes, and then when the window is closed the changes are reset to the values they were before opening it. I tried a complete uninstall and reinstall of dayz and the editor, but still doing the same thing.

**Comment by Craigo1972** [comment]
Same here for me, cant use page up page down to adjust height while placing as well. Also tried repair, full delete and reinstall.

Thanks, FYI love Dayz-Editor magic mod, GG

**Comment by bl0ke** [comment]
Confirmed. The scale box still works (tested using mousewheel) but the size and rotation boxes do not.

**Comment by InclementDab** [comment]
Solved in todays update

**Comment by Craigo1972** [comment]
Cheers mate legend

**Comment by BBTDB** [comment]
Jeez, that was quick. Impressive. Most impressive. On Jun 24, 2023, at 12:45, Tyler Paul ***@***.***> wrote:﻿
Closed #117 as completed.
