### ISSUE TITLE
Loading with Expansion crashes

### ISSUE THREAD

**Issue by skulldrago** [InclementDab/DayZ-Editor#132]
When DayZ Expansion Pack is active the Editor starts after choosing the map it crashes

**Comment by TheDevilsKnock** [comment]
As specified in the [Wiki](https://github.com/InclementDab/DayZ-Editor/wiki/2.-Installing-DayZ-Editor) on Editor you need to use
[DayZ-Expansion-Map-Assets](https://steamcommunity.com/sharedfiles/filedetails/?id=2792983824&searchtext=expansion)

**Comment by bzed** [comment]
@TheDevilsKnock well, loading that crashes the editor for me, I think it keeps eating ram until it crashes (yes, I have enough of it...)
