### ISSUE TITLE
 editor not working right 

### ISSUE THREAD

**Issue by midnightoss** [InclementDab/DayZ-Editor#136]
I do work for a server doing editor work for them when trying to load in a C file it puts the items invisible the only way to get it to be visible is to enable physics then turn it off and it's all there you have to hit the undo button for it in order for it to be somewhat like it should be but it's still very off is there a way to fix this Thanks

**Comment by TheDevilsKnock** [comment]
Github issues are for the codebase. 
Please report mod bugs on our discord.
