### ISSUE TITLE
[Suggestion] Snap Camera to Selected Object

### ISSUE THREAD

**Issue by JohnnyBravo2014** [InclementDab/DayZ-Editor#63]
Could we get a key you can get after selecting an object that you have placed down that will snap the camera within x distance of that object.

**Comment by InclementDab** [comment]
We have a Toggle Focus on camera but it felt super restrictive and non-intuitive. I can easily hotkey it for testing if we want to fool around with it

**Comment by JohnnyBravo2014** [comment]
Ok. Yeah I had an item that completely went missing but I could see it still in the placed object sidebar. Ended up just deleting it and placing a new one lol. Thanks for the reply!

**Comment by InclementDab** [comment]
You probably hid the object. Right click on the object on the right bar and click 'show'

**Comment by JohnnyBravo2014** [comment]
I did do that but it never showed back up. I even manually adjusted the coordinates and tried hitting show as well. No biggy though.
