### ISSUE TITLE
Editor Crash 0xC0000005 = STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by zvukoper** [InclementDab/DayZ-Editor#79]
I worked pretty stable a month ago. Now it crashes. I load an empty map, place a couple of objects. Crash.

![изображение](https://user-images.githubusercontent.com/511118/116649260-5ae4cf80-a998-11eb-976d-9729a0abecf8.png)

Log:

> NULL pointer to instance
> Class: 'DayZIntroScenePC'
> Function: 'ResetIntroCamera'
> Stack trace:
> scripts/5_Mission/dayzintroscene.c:125
> scripts/5_Mission/gui\newui\mainmenu\mainmenu.c:82
> DayZEditor/scripts/5_Mission/dayzeditor\mainmenu.c:8
> 
> Runtime mode
> CLI params: name Znahar mod C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@BuilderItems;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@CF;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@DayZ-Editor
> NULL pointer to instance
> Class: 'Editor'
> Function: 'LoadBanData'
> Stack trace:
> DayZEditor/scripts/4_World/dayzeditor\classes\editor.c:1005
> DayZEditor/scripts/4_World/dayzeditor\classes\editor.c:88
> DayZEditor/scripts/4_World/dayzeditor\classes\editor.c:145
> DayZEditor/scripts/4_World/dayzeditor\modules\editorclient.c:74
> JM/CF/Scripts/4_World/communityframework\module\jmmodulemanager.c:113
> JM/CF/Scripts/5_Mission/communityframework\mission\missiongameplay.c:24
> 
> Runtime mode
> CLI params: name Znahar mod C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@BuilderItems;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@CF;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@DayZ-Editor
> NULL pointer to instance
> Class: 'DayZIntroScenePC'
> Function: 'ResetIntroCamera'
> Stack trace:
> scripts/5_Mission/dayzintroscene.c:125
> scripts/5_Mission/gui\newui\mainmenu\mainmenu.c:82
> DayZEditor/scripts/5_Mission/dayzeditor\mainmenu.c:8
> 
> Runtime mode
> CLI params: name Znahar mod C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@BuilderItems;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@CF;C:\Program Files (x86)\Steam\steamapps\common\DayZ\!Workshop\@DayZ-Editor
> 
> 
>

**Comment by InclementDab** [comment]
Fixed in this afternoons hotfix, update is live on steam
